version: "3.9"

services:
  web:
    image: ${ECR_IMAGE:-000000000000.dkr.ecr.us-east-2.amazonaws.com/inova:latest}
    pull_policy: always
    ports:
      - "80:80"
    environment:
      - MAILERLITE_API_KEY=${MAILERLITE_API_KEY}
    restart: unless-stopped
